classdef HabitTracker_tests < matlab.unittest.TestCase
    
    properties (Constant)
        xml_file_heading = '<?xml version="1.0" encoding="utf-8"?>';
        habit_xml_file = 'xml_test.xml';
    end
    
    methods(TestMethodSetup)
        function createObject(testCase)
        end
    end
    
    methods(TestMethodTeardown)
        function destroyObject(testCase)
            delete(HabitTracker_tests.habit_xml_file);
        end
    end

    methods (Static)
    end
    
    methods(Test)
        function should_not_modify_xml_file_when_structure_is_left_the_same(testCase)
            % Given
            xml_existing_text = sprintf(['%s\n',...
            '<global>\n',...
                '<day date="21/07/2018">\n',...
                    '<element tag="Cold Approach">1</element>\n',...
                    '<element tag="Ejercicio">0</element>\n',...
                    '<element tag="Gratitud y Evidence Log">0</element>\n',...
                    '<element tag="Intencion escrita">1</element>\n',...
                    '<element tag="Meditacion matutina">1</element>\n',...
                    '<element tag="Meditacion vespertina">0</element>\n',...
                    '<element tag="Planificacion matinal">1</element>\n',...
                '</day>\n',...
                '<day date="20/07/2018">\n',...
                    '<element tag="Cold Approach">0</element>\n',...
                    '<element tag="Ejercicio">1</element>\n',...
                    '<element tag="Gratitud y Evidence Log">0</element>\n',...
                    '<element tag="Intencion escrita">1</element>\n',...
                    '<element tag="Meditacion matutina">1</element>\n',...
                    '<element tag="Meditacion vespertina">0</element>\n',...
                    '<element tag="Planificacion matinal">1</element>\n',...
                '</day>\n',...
            '</global>'
            ], HabitTracker_tests.xml_file_heading);
            f = fopen(HabitTracker_tests.habit_xml_file, 'w');
            fwrite(f, xml_existing_text);
            fclose(f);

            % When
            existing_habits_table = habitXML2table(HabitTracker_tests.habit_xml_file);
            existing_habits_table = [];
            habitTable2XML(existing_habits_table, HabitTracker_tests.habit_xml_file);

            % Then
            xml_text = fileread(HabitTracker_tests.habit_xml_file);
            testCase.assertEqual(xml_text, xml_existing_text);
        end
    end
end